apiVersion: v1
kind: Namespace
metadata:
  name: eks-fargate-nodes

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: eks-fargate-nodes
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
