#!/bin/bash

CERTIFCATE_ARN=$1
CERTIFICATE_FILE=$2
STRING="SSL_CERTIFICATE"

#sed 's/SSL_CERTIFICATE/'"${CERTIFCATE_ARN}"'/' $CERTIFICATE_FILE
#sed 's#SSL_CERTIFICATE#'"${CERTIFCATE_ARN}"'#' $CERTIFICATE_FILE
sed -i.bak 's#SSL_CERTIFICATE#'"${CERTIFCATE_ARN}"'#g' $CERTIFICATE_FILE
