#!/bin/bash

SUBNET_1_ID=$1
SUBNET_2_ID=$2
SUBNET_3_ID=$3
DOMAIN_NAME=$4
SSL_CERTIFICATE=$5
MANIFEST_FILE=$6
STRING_1="SUBNET_1"
STRING_2="SUBNET_2"
STRING_3="SUBNET_3"
STRING_4="DOMAIN_NAME"
STRING_5="SSL_CERTIFICATE"
#sed 's/SSL_CERTIFICATE/'"${CERTIFCATE_ARN}"'/' $CERTIFICATE_FILE
#sed 's#SSL_CERTIFICATE#'"${CERTIFCATE_ARN}"'#' $CERTIFICATE_FILE
sed -i.bak 's#'${STRING_1}'#'"${SUBNET_1_ID}"'#g' $MANIFEST_FILE
sed -i.bak 's#'${STRING_2}'#'"${SUBNET_2_ID}"'#g' $MANIFEST_FILE
sed -i.bak 's#'${STRING_3}'#'"${SUBNET_3_ID}"'#g' $MANIFEST_FILE
sed -i.bak 's#'${STRING_4}'#'"${DOMAIN_NAME}"'#g' $MANIFEST_FILE
sed -i.bak 's#'${STRING_5}'#'"${SSL_CERTIFICATE}"'#g' $MANIFEST_FILE
